name: CI

on:
  # Triggers the workflow on push events
  push:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: bentoml setup
        uses: bentoml/setup-bentoml-action@v1
        with:
          python-version: '3.10'
          bentoml-version: 'main'
      
      - name: Install Dependencies
        run: pip install -r linux_requirements.txt
        
      - name: build the bento
        uses: bentoml/build-bento-action@v1
        id: bento
        env:
          URL: ${{ secrets.URL }}

      - name: BentoML Containerize
        uses: bentoml/containerize-action@v1
        with:
          bento-tag: ${{ steps.bento.outputs.bento-tag }}
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600
      
      - name: Tag image
        run:
          docker tag ${{ steps.bento.outputs.bento-tag }} registry.digitalocean.com/test-ml-container/c6prhswwdw76lc4z
      
      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/test-ml-container/c6prhswwdw76lc4z